import base64
import re
import time
from typing import Dict, Optional
import httpx


class GitHubService:
    """Pushes generated workspace files to a new GitHub repository via REST API."""

    API = "https://api.github.com"

    def __init__(self, token: str):
        self.token = token
        self.headers = {
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _slugify(self, text: str) -> str:
        slug = re.sub(r"[^\w\s-]", "", text.lower())
        slug = re.sub(r"[\s_]+", "-", slug).strip("-")
        return slug[:80] or "ai-project"

    def _get(self, path: str) -> dict:
        with httpx.Client(timeout=20) as client:
            r = client.get(f"{self.API}{path}", headers=self.headers)
            r.raise_for_status()
            return r.json()

    def _post(self, path: str, payload: dict) -> dict:
        with httpx.Client(timeout=30) as client:
            r = client.post(f"{self.API}{path}", headers=self.headers, json=payload)
            r.raise_for_status()
            return r.json()

    def _put(self, path: str, payload: dict) -> dict:
        with httpx.Client(timeout=30) as client:
            r = client.put(f"{self.API}{path}", headers=self.headers, json=payload)
            r.raise_for_status()
            return r.json()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def get_authenticated_user(self) -> str:
        data = self._get("/user")
        return data["login"]

    def create_repo(self, username: str, repo_name: str, description: str) -> dict:
        """Create a new private repo; returns the repo JSON object."""
        return self._post(
            "/user/repos",
            {
                "name": repo_name,
                "description": description,
                "private": True,
                "auto_init": True,
            },
        )

    def push_files(
        self,
        username: str,
        repo_name: str,
        files: Dict[str, str],
        commit_message: str,
    ) -> str:
        """
        Commit multiple files to the default branch in one go via the
        Git Data API (tree + commit). Returns the new commit SHA.
        """
        branch_ref = self._get(f"/repos/{username}/{repo_name}/git/ref/heads/main")
        base_sha = branch_ref["object"]["sha"]

        base_commit = self._get(f"/repos/{username}/{repo_name}/git/commits/{base_sha}")
        base_tree_sha = base_commit["tree"]["sha"]

        tree_nodes = []
        for path, content in files.items():
            # Encode content as base64 blob
            blob = self._post(
                f"/repos/{username}/{repo_name}/git/blobs",
                {
                    "content": base64.b64encode(content.encode()).decode(),
                    "encoding": "base64",
                },
            )
            tree_nodes.append(
                {"path": path, "mode": "100644", "type": "blob", "sha": blob["sha"]}
            )

        new_tree = self._post(
            f"/repos/{username}/{repo_name}/git/trees",
            {"base_tree": base_tree_sha, "tree": tree_nodes},
        )

        new_commit = self._post(
            f"/repos/{username}/{repo_name}/git/commits",
            {
                "message": commit_message,
                "tree": new_tree["sha"],
                "parents": [base_sha],
            },
        )

        # Advance the branch ref
        self._put(
            f"/repos/{username}/{repo_name}/git/refs/heads/main",
            {"sha": new_commit["sha"]},
        )

        return new_commit["sha"]

    def publish_workspace(
        self,
        objective: str,
        session_id: str,
        files: Dict[str, str],
    ) -> Dict[str, str]:
        """
        High-level helper: create repo + push all files.
        Returns dict with repo_url, commit_sha, repo_name.
        """
        username = self.get_authenticated_user()
        slug = self._slugify(objective)
        timestamp = int(time.time()) % 100000
        repo_name = f"ai-team-{slug}-{timestamp}"
        description = f"Auto-generated by Autonomous Software Team | Session {session_id}"

        repo = self.create_repo(username, repo_name, description)
        repo_url = repo["html_url"]

        # Always include a README
        files_to_push = dict(files)
        if "README.md" not in files_to_push:
            files_to_push["README.md"] = (
                f"# {repo_name}\n\n> {description}\n\n"
                f"**Objective:** {objective}\n\n"
                "Generated by the [Autonomous Multi-Agent Software Team](https://github.com)."
            )

        commit_sha = self.push_files(
            username=username,
            repo_name=repo_name,
            files=files_to_push,
            commit_message=f"feat: autonomous agent delivery for '{objective[:72]}'",
        )

        return {
            "repo_url": repo_url,
            "commit_sha": commit_sha,
            "repo_name": repo_name,
            "username": username,
        }
