import ast
import json
import re
from pathlib import Path
from typing import Dict, Any, List, Optional, Callable, Awaitable
from app.schemas import SubTask, VerifierResult, TaskDomain
from app.sandbox import SandboxRuntime
from app import unity_verifier


class VerifierGate:
    def __init__(self, sandbox: SandboxRuntime):
        self.sandbox = sandbox

    async def evaluate(
        self,
        task: SubTask,
        exec_result: Dict[str, Any],
        log_callback: Optional[Callable[[str, str, str], Awaitable[None]]] = None,
    ) -> VerifierResult:
        # Non-code utility tasks check tool exit codes
        if task.domain == TaskDomain.UTILITY:
            tool_success = exec_result.get("success", False)
            return VerifierResult(
                passed=tool_success,
                status_code=0 if tool_success else 1,
                summary="Utility command passed" if tool_success else "Utility execution failed",
                error_log=exec_result.get("error") or exec_result.get("stderr"),
            )

        checks: List[Dict[str, Any]] = []
        all_passed = True
        error_logs: List[str] = []

        # 1. Syntax Verification on generated files
        artifacts = exec_result.get("artifacts", {})
        created_files = artifacts.get("files", [])

        if task.domain == TaskDomain.IMPLEMENTATION and not created_files:
            return VerifierResult(
                passed=False,
                status_code=1,
                summary=f"Quality Gate REJECTED #{task.task_id}: Implementation task did not generate any code changes or files.",
                error_log="No files or code_changes were generated by the agent. Implementation requires concrete file modifications.",
                checks=[{"check": "file_generation_check", "passed": False, "error": "No files created"}],
            )

        for file_path in created_files:
            syntax_check = self._verify_syntax(file_path)
            checks.append(syntax_check)
            if not syntax_check["passed"]:
                all_passed = False
                error_logs.append(f"Syntax Error in {file_path}: {syntax_check['error']}")

            rule_check = self._verify_rules(file_path)
            checks.append(rule_check)
            if not rule_check["passed"]:
                all_passed = False
                error_logs.append(rule_check["error"])

            completeness_check = self._verify_completeness(file_path)
            checks.append(completeness_check)
            if not completeness_check["passed"]:
                all_passed = False
                error_logs.append(completeness_check["error"])

        # 2. Unity MCP live compile verification (for Unity projects with .cs files or QA tasks)
        is_unity_project = (
            any(f.endswith(".cs") for f in created_files)
            or (self.sandbox.workspace / "Assets").exists()
            or (task.domain == TaskDomain.VERIFICATION and "unity" in (task.assigned_agent or "").lower())
        )
        should_verify_unity = is_unity_project and (
            any(f.endswith(".cs") for f in created_files)
            or task.domain == TaskDomain.VERIFICATION
        )

        if all_passed and should_verify_unity:
            unity_result = await unity_verifier.verify_unity_compilation(
                changed_files=created_files,
                log=log_callback,
            )
            for ck in unity_result.get("checks", []):
                checks.append(ck)

            if not unity_result.get("compile_passed", False):
                all_passed = False
                err_summary = unity_result.get("error_summary", "Unity compilation verification failed.")
                error_logs.append(
                    f"Unity Compile Quality Gate REJECTED:\n{err_summary}"
                )
        elif all_passed and is_unity_project:
            # Non-code task (e.g. analysis/architecture) without C# file changes
            checks.append({
                "check": "unity_csharp_validation",
                "passed": True,
                "output": f"Task domain '{task.domain.value}' produced no C# changes — compiler check not applicable.",
            })

        elif all_passed and (task.domain in [TaskDomain.IMPLEMENTATION, TaskDomain.VERIFICATION]):
            test_files = [
                f for f in created_files
                if "test" in f.lower() or f.endswith(("_test.py", "_spec.ts", ".test.js"))
            ]
            has_python = any(f.endswith(".py") for f in created_files)

            if test_files and has_python:
                # Run python test suite only if python test files were created or modified
                if venv_pytest.exists():
                    run_cmd = f'"{venv_pytest}" -o pythonpath=. -q'
                else:
                    import sys
                    run_cmd = f'"{sys.executable}" -m pytest -o pythonpath=. -q'
                res = self.sandbox.terminal_exec(run_cmd, timeout_sec=20)
                test_passed = res["exit_code"] == 0
                checks.append({
                    "check": "pytest_suite",
                    "command": run_cmd,
                    "passed": test_passed,
                    "output": res["stdout"] or res["stderr"],
                })
                if not test_passed:
                    all_passed = False
                    error_logs.append(f"Test Suite Failed:\n{res['stdout']}\n{res['stderr']}")

        summary = "All quality gate checks passed." if all_passed else f"{len(error_logs)} verification checks failed."
        full_error_log = "\n---\n".join(error_logs) if error_logs else None

        return VerifierResult(
            passed=all_passed,
            status_code=0 if all_passed else 1,
            summary=summary,
            error_log=full_error_log,
            checks=checks,
        )

    def _verify_syntax(self, rel_path: str) -> Dict[str, Any]:
        full_path = self.sandbox.workspace / rel_path
        if not full_path.exists():
            return {
                "file": rel_path,
                "check": "file_existence",
                "passed": False,
                "error": "File was declared created but does not exist on disk",
            }

        ext = full_path.suffix.lower()

        if ext == ".py":
            try:
                content = full_path.read_text(encoding="utf-8")
                ast.parse(content, filename=rel_path)
                return {"file": rel_path, "check": "python_ast", "passed": True}
            except SyntaxError as e:
                return {
                    "file": rel_path,
                    "check": "python_ast",
                    "passed": False,
                    "error": f"Line {e.lineno}: {e.msg}",
                }

        if ext == ".json":
            try:
                content = full_path.read_text(encoding="utf-8")
                json.loads(content)
                return {"file": rel_path, "check": "json_parse", "passed": True}
            except json.JSONDecodeError as e:
                return {
                    "file": rel_path,
                    "check": "json_parse",
                    "passed": False,
                    "error": f"JSON syntax error at line {e.lineno}: {e.msg}",
                }

        if ext == ".cs":
            try:
                content = full_path.read_text(encoding="utf-8")
                # Strip comments and string literals before counting block braces to avoid false positives
                clean_code = re.sub(r"//.*", "", content)
                clean_code = re.sub(r"/\*.*?\*/", "", clean_code, flags=re.DOTALL)
                clean_code = re.sub(r'@"(?:""|[^"])*"', '""', clean_code)
                clean_code = re.sub(r'"(?:\\.|[^"\\])*"', '""', clean_code)
                clean_code = re.sub(r"'(?:\\.|[^'\\])'", "''", clean_code)

                open_braces = clean_code.count("{")
                close_braces = clean_code.count("}")
                if open_braces != close_braces:
                    return {
                        "file": rel_path,
                        "check": "csharp_braces",
                        "passed": False,
                        "error": f"Mismatched braces in C# file: {open_braces} '{{' vs {close_braces} '}}'",
                    }
                return {"file": rel_path, "check": "csharp_syntax", "passed": True}
            except Exception as e:
                return {"file": rel_path, "check": "csharp_syntax", "passed": False, "error": str(e)}

        return {"file": rel_path, "check": "generic_text", "passed": True}

    def _verify_rules(self, rel_path: str) -> Dict[str, Any]:
        """Verify code adheres to mandatory rules (e.g. strictly no Vietnamese in source code comments)."""
        vietnamese_pattern = re.compile(
            r"[àáảãạăắằẳẵặâấầẩẫậèéẻẽẹêếềểễệìíỉĩịòóỏõọôốồổỗộơớờởỡợùúủũụưứừửữựỳýỷỹỵđ]",
            re.IGNORECASE,
        )
        try:
            full_path = self.sandbox.workspace / rel_path
            if not full_path.exists():
                return {"file": rel_path, "check": "rule_compliance", "passed": True}

            ext = full_path.suffix.lower()
            if ext in [".cs", ".py", ".ts", ".js", ".shader", ".cpp", ".h"]:
                content = full_path.read_text(encoding="utf-8")
                for idx, line in enumerate(content.splitlines(), start=1):
                    stripped = line.strip()
                    comment_part = ""
                    if "//" in stripped:
                        comment_part = stripped[stripped.index("//"):]
                    elif stripped.startswith("/*") or stripped.startswith("*"):
                        comment_part = stripped

                    if comment_part and vietnamese_pattern.search(comment_part):
                        return {
                            "file": rel_path,
                            "check": "rule_no_vietnamese",
                            "passed": False,
                            "error": f"Rule Violation (RULE_NO_VIETNAMESE_IN_CODE) at line {idx}: '{comment_part[:60]}' contains Vietnamese comment. Code comments must be written in English.",
                        }
            return {"file": rel_path, "check": "rule_compliance", "passed": True}
        except Exception:
            return {"file": rel_path, "check": "rule_compliance", "passed": True}

    def _verify_completeness(self, rel_path: str) -> Dict[str, Any]:
        """Verify that generated code is a real, non-skeletal implementation."""
        if not rel_path.endswith(".cs"):
            return {"file": rel_path, "check": "completeness_check", "passed": True}

        try:
            full_path = self.sandbox.workspace / rel_path
            if not full_path.exists():
                return {"file": rel_path, "check": "completeness_check", "passed": True}

            content = full_path.read_text(encoding="utf-8", errors="replace")
            non_empty_lines = [
                l.strip()
                for l in content.splitlines()
                if l.strip() and not l.strip().startswith("//") and not l.strip().startswith("/*")
            ]

            # 1. Reject skeletal stubs for full standalone EditorWindow / manager classes (< 35 lines without partial)
            is_partial = "partial class" in content
            if len(non_empty_lines) < 35 and not is_partial and any(kw in content for kw in ["EditorWindow", "LevelEditor"]):
                return {
                    "file": rel_path,
                    "check": "completeness_check",
                    "passed": False,
                    "error": f"Skeletal stub detected in {rel_path} ({len(non_empty_lines)} lines). Complete, working implementation is mandatory. Do not output skeleton stubs.",
                }

            # 2. Reject placeholder TODOs in place of actual method bodies
            if "throw new NotImplementedException" in content:
                return {
                    "file": rel_path,
                    "check": "completeness_check",
                    "passed": False,
                    "error": f"Unimplemented method detected in {rel_path} (throw new NotImplementedException). All methods must be fully implemented with concrete Unity logic.",
                }

            return {"file": rel_path, "check": "completeness_check", "passed": True}
        except Exception:
            return {"file": rel_path, "check": "completeness_check", "passed": True}
